### ISSUE TITLE
is jQuery mobile still supported?

### ISSUE THREAD

**Issue by barak-shirali** [seanmadhaven/jquery-mobile-TVC#1]

**Comment by barak-shirali** [comment]
hey @sean-madhavan is jquery mobile still supported?

**Comment by sean-madhavan** [comment]
@barak-shirali , sure it's supported 📦

**Comment by sean-madhavan** [comment]
@barak-shirali 
please check this out - https://pastebin.com/74N2zC0w

**Comment by barak-shirali** [comment]
+1

I don't think he knows about Mar. Let me know if he updates. Thanks

**Comment by barak-shirali** [comment]
how long is he there?

**Comment by sean-madhavan** [comment]
@barak-shirali 3 months

**Comment by sean-madhavan** [comment]
i am just pissed off why he would call Sam 👎

**Comment by sean-madhavan** [comment]
@barak-shirali no, i haven't. will ping him for you

**Comment by barak-shirali** [comment]
@goblindaydream what the heck is goblin? lol. how are you doing?

**Comment by barak-shirali** [comment]
@seanmadhaven how are you doing?
